version: '3.7'

services:
  app:
    container_name: python_api_geral
    build:
      dockerfile: ./app/Dockerfile
      context: .
    #image: python:latest
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo

  identificacao:
    container_name: python_api_identificacao
    build:
      dockerfile: ./identificacao/Dockerfile
      context: .
    #image: python:latest
    restart: always
    ports:
      - '5010:5000'
    volumes:
      - ./identificacao:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo

  simulacao:
    container_name: python_api_simulacao
    build:
      dockerfile: ./simulacao/Dockerfile
      context: .
    #image: python:latest
    restart: always
    ports:
      - '5020:5000'
    volumes:
      - ./simulacao:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha123
      MONGO_INITDB_DATABASE: desafio_back
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  mongo-data:
  mongo-configdb:
  